// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVF_ieenorEVJlEwRBMJl1HCLyxr5vUOM',
    appId: '1:209567707207:android:7c23fbb9e41cffd9088162',
    messagingSenderId: '209567707207',
    projectId: 'digital-telecom-170b0',
    databaseURL: 'https://digital-telecom-170b0-default-rtdb.firebaseio.com',
    storageBucket: 'digital-telecom-170b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk-5vOvaGyV3eobICmagRgmNwxD3FZbcE',
    appId: '1:209567707207:ios:69c715bd5968e777088162',
    messagingSenderId: '209567707207',
    projectId: 'digital-telecom-170b0',
    databaseURL: 'https://digital-telecom-170b0-default-rtdb.firebaseio.com',
    storageBucket: 'digital-telecom-170b0.appspot.com',
    iosClientId: '209567707207-kt1g1c02if9fl24dogoslcbgii9ucrbg.apps.googleusercontent.com',
    iosBundleId: 'com.example.recharge',
  );
}
